services:

  desktop:
    build: desktop
    restart: unless-stopped
    healthcheck:
      test: test -f /ready
    ports:
      - 5900:5900
      - 6000:6000

#  desktop1:
#    build: desktop
#    restart: unless-stopped
#    healthcheck:
#      test: test -f /ready
#    ports:
#      - 5901:5900
#      - 6001:6000


  tools:
    build: tools
    restart: unless-stopped
    depends_on:
      desktop:
        condition: service_healthy
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - tools-data:/tools-data
    environment:
      - DISPLAY=desktop:0
      - XDG_RUNTIME_DIR=/tmp

  fluidsynth:
    build: fluidsynth
    restart: unless-stopped
    ports:
      - 9800:9800
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - media-data:/media-data
    environment:
      - XDG_RUNTIME_DIR=/tmp

  halv1:
    build: halv
    restart: unless-stopped
    command: pw-jack jalv -H 5678 http://helander.network/plugins/lv2/unison
    depends_on:
      desktop:
        condition: service_healthy
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    environment:
      - DISPLAY=desktop:0
      - XDG_RUNTIME_DIR=/tmp

#  lv2test:
#    build: lv2test
#    restart: unless-stopped
#    depends_on:
#      desktop:
#        condition: service_healthy
#    volumes:
#      - /run/user/1000/pipewire-0:/tmp/pipewire-0
#    environment:
#      - DISPLAY=desktop:0
#      - XDG_RUNTIME_DIR=/tmp


#  ingen:
#    build: ingen
#    restart: unless-stopped
#    depends_on:
#      desktop:
#        condition: service_healthy
#    volumes:
#      - /run/user/1000/pipewire-0:/tmp/pipewire-0
#    environment:
#      - DISPLAY=desktop:0
#      - XDG_RUNTIME_DIR=/tmp

##  volmgmt:
##    image: debian
##    command: sleep infinity
##    volumes:
##      - media-data:/media-data
##      - tools-data:/tools-data

volumes:
  media-data:
  tools-data:
