#!/bin/bash
 
if [ "$1" = configure ]; then
   systemctl daemon-reload
   systemctl enable media-soundqube.mount
   systemctl stop media-soundqube.mount
   systemctl start media-soundqube.mount
   udevadm control --reload-rules
fi

