FROM ubuntu:20.04  

#Install the necessary packages 
RUN apt-get update && \     
    apt-get install -y x11-apps  


#Run a simple GUI application (xeyes as an example)
CMD ["xeyes"]
#CMD ["sleep","1000000"]
